# Generated by Django 6.0.3 on 2026-04-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['course', 'number']},
        ),
        migrations.AddField(
            model_name='semester',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MSC', 'MSC')], default='BCA', max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'course')},
        ),
    ]
